[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "thiagola92", email = "thiagola92@gmail.com"},
]
dependencies = [
    "requests>=2.28.2",
    "parsel>=1.7.0",
    "brotli>=1.0.9",
    "setuptools>=67.6.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
